"""
Self-Driving Lab Controller (v2026)

This agent acts as the interface between the AI reasoning layer (Drug Discovery Agents)
and the physical world (Liquid Handling Robots like Opentrons/Tecan).

Capabilities:
1. Translate "High Level Intent" (e.g., "Make 10mM solution") into "Python Protocol".
2. Safety check volumes and concentrations.
3. Optimize plate layouts.
"""

from typing import Dict, List, Optional

class LabProtocolGenerator:
    def __init__(self, robot_type: str = "Opentrons_OT2"):
        self.robot_type = robot_type

    def generate_protocol(self, intent: str, reagents: List[Dict]) -> str:
        """
        Generates a Python script for the robot to execute.
        """
        # In a real system, this would use an LLM fine-tuned on the Opentrons API.
        # Here we use a template-based approach for the prototype.
        
        protocol_header = f"""
from opentrons import protocol_api

metadata = {{
    'apiLevel': '2.13',
    'protocolName': '{intent}',
    'author': 'AI Agent',
    'description': 'Auto-generated by Self-Driving Lab Controller'
}}

def run(protocol: protocol_api.ProtocolContext):
    # Labware Setup
    plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 1)
    tiprack = protocol.load_labware('opentrons_96_tiprack_300ul', 2)
    pipette = protocol.load_instrument('p300_single_gen2', 'right', tip_racks=[tiprack])
    
    # Reagent Setup
"""
        
        commands = []
        well_index = 0
        for reagent in reagents:
            name = reagent.get("name", "Unknown")
            vol = reagent.get("volume_ul", 0)
            
            commands.append(f"    # Transferring {name}")
            commands.append(f"    pipette.pick_up_tip()")
            commands.append(f"    pipette.aspirate({vol}, plate.wells()[{well_index}]) # Source placeholder")
            commands.append(f"    pipette.dispense({vol}, plate.wells()[{well_index + 1}]) # Dest placeholder")
            commands.append(f"    pipette.drop_tip()")
            well_index += 2
            
        return protocol_header + "\n".join(commands)

    def safety_check(self, protocol_code: str) -> bool:
        """
        Scans the generated code for dangerous operations (e.g., mixing incompatibles).
        """
        # Mock logic
        forbidden_mixes = ["acid", "cyanide"] # Simplistic keyword check
        for term in forbidden_mixes:
            if term in protocol_code.lower():
                print(f"SAFETY ALERT: Found hazardous term '{term}' in protocol.")
                return False
        return True

if __name__ == "__main__":
    controller = LabProtocolGenerator()
    
    experiment_intent = "Dilute compound library for screening"
    reagents_list = [
        {"name": "Compound_A", "volume_ul": 50},
        {"name": "Buffer_PBS", "volume_ul": 100}
    ]
    
    code = controller.generate_protocol(experiment_intent, reagents_list)
    
    print("--- Generated Robot Protocol ---")
    print(code)
    
    if controller.safety_check(code):
        print("\n[Safety System]: Protocol Verified. Ready to Upload.")
    else:
        print("\n[Safety System]: Protocol REJECTED.")
