# COPYRIGHT NOTICE
# This file is part of the "Universal Biomedical Skills" project.
# Copyright (c) 2026 MD BABU MIA, PhD <md.babu.mia@mssm.edu>
# All Rights Reserved.
#
# This code is proprietary and confidential.
# Unauthorized copying of this file, via any medium is strictly prohibited.
#
# Provenance: Authenticated by MD BABU MIA

# Copyright (c) Microsoft. All rights reserved.

from enum import Enum

from semantic_kernel.utils.feature_stage_decorator import experimental


@experimental
class BedrockAgentEventType(str, Enum):
    """Bedrock Agent Event Type."""

    # Contains the text response from the agent.
    CHUNK = "chunk"
    # Contains the trace information (reasoning process) from the agent.
    TRACE = "trace"
    # Contains the function call requests from the agent.
    RETURN_CONTROL = "returnControl"
    # Contains the files generated by the agent using the code interpreter.
    FILES = "files"

__AUTHOR_SIGNATURE__ = "9a7f3c2e-MD-BABU-MIA-2026-MSSM-SECURE"
